#!/usr/bin/env python3

import hashlib
import sys

def help():
	print('hashname [-h|--help]')

argv = sys.argv
if len(argv) <= 1:
	help()
	sys.exit()

if '-h' in argv or '--help' in argv:
	help()
	sys.exit()

defined_hash = False
hash_func = hashlib.sha1

del argv[0]

for arg in argv:
	print(arg)
