#!/usr/bin/env python3


# Add -- for files


import hashlib
import sys
import os
import os.path

def help():
	print('hashname [-h|--help]')

argv = sys.argv
if len(argv) <= 1:
	help()
	sys.exit()

if '-h' in argv or '--help' in argv:
	help()
	sys.exit()

def seperate(str):
	parts = str.split('.')
	if len(parts) == 1:
		return {'root' : str, 'ext' : ''}

	ext = parts[len(parts) - 1]
	del parts[len(parts) - 1]

	root = parts[0]
	del parts[0]
	for part in parts:
		root += '.' + part
	return {'root' : root, 'ext' : ext}

def name(hashname, sep):
	if '' == sep['ext']:
		return hashname
	return hashname + '.' + sep['ext']

defined_hash = False
hash_func = hashlib.sha1

del argv[0]

for arg in argv:
	if os.path.isfile(arg):
		f = open(arg, 'rb')
		hashname = hash_func(f.read()).hexdigest()
		sep = seperate(arg)
		if arg == name(hashname, sep):
			# Already renamed, delete if different name 
			if name(hashname, sep) != arg:
				os.remove(arg)
		else:
			os.rename(arg, name(hashname, sep))
	else:
		print("%s is not a file" % (arg))

